### ISSUE TITLE
Find a good solution for update_at on the postgresql backend

### ISSUE THREAD

**Issue by jerben** [oxidizing/sihl#135]

**Comment by tmattio** [comment]
Hey @jerben 🙂 

I was looking into Sihl (really nice project!!) and stumbled upon this issue, so I thought I'd share this piece of code that I use for `updated_at` fields:

```sql
CREATE OR REPLACE FUNCTION "public"."set_current_timestamp_updated_at"()
RETURNS TRIGGER AS $$
DECLARE
  _new record;
BEGIN
  _new := NEW;
  _new."updated_at" = now();
  RETURN _new;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "set_public_users_updated_at"
BEFORE UPDATE ON "public"."users"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_current_timestamp_updated_at"();
```

This will set the value of `updated_at` to `now()` every time the row is modified.

Not sure this is what you meant, but I hope it helps 😄

**Comment by jerben** [comment]
Hey @tmattio, thanks a lot for the kind words and the nice input! :slightly_smiling_face: 

Once the MariaDB driver supports non-prepared statements, this will be most likely the solution.
https://github.com/paurkedal/ocaml-caqti/issues/42

**Comment by tmattio** [comment]
Good to know, thanks for the link!

**Comment by jerben** [comment]
@tmattio  I just realized this is only an issue for Postgres :slightly_smiling_face:  Last time I checked the issue for the MariaDB driver doesn't really exist for the Postgres driver, so this works! :+1:

**Comment by jerben** [comment]
For now we are doing that on application level so it is repo independent.
