### ISSUE TITLE
Create ExcelService

### ISSUE THREAD

**Issue by aronerben** [oxidizing/sihl#159]
- Should be `string list list -> excel file`
- Can use StorageService
- LibreOffice: which minimal installation? what is input data? stdin? file?
- LibreOffice exterior
- https://github.com/andrenth/ocaml-mariadb/blob/master/opam for depetxs LibreOffice installation
- https://ocsigen.org/lwt/3.2.1/api/Lwt_process to run a LO task async

**Comment by jerben** [comment]
Fixed.
