### ISSUE TITLE
Remove unit from arguments for all functions that don't have optional argument

### ISSUE THREAD

**Issue by aronerben** [oxidizing/sihl#196]
Stuff like
```ocaml
  val find_opt : Core.Ctx.t -> value:string -> unit -> Token_core.t option Lwt.t
```
does not need a unit, remove it!

**Comment by jerben** [comment]
Fixed.

**Comment by aronerben** [comment]
@jerben Did you fix it throughout all of the code?

**Comment by jerben** [comment]
@aronerben I haven't seen any other occurrences, at least not in the service signatures.

**Comment by aronerben** [comment]
@jerben Ok cool, thx!
