### ISSUE TITLE
Admin UI Service

### ISSUE THREAD

**Issue by jerben** [oxidizing/sihl#225]
## Goal

The goal is to implement an Admin UI Service that can be used to register Admin UIs. Admin UIs are routers with one or multiple CRUD resources attached that can be mounted to some prefix, like /admin.

Every service contributes its Admin UI, so there is a similar out-of-box experience as with Django.

**Comment by jerben** [comment]
This is a duplicate of https://github.com/oxidizing/sihl/issues/225

**Comment by aronerben** [comment]
> This is a duplicate of #225

A duplicate of itself? ;)
