### ISSUE TITLE
Improve sihl-starter

### ISSUE THREAD

**Issue by jerben** [oxidizing/sihl#227]
## Goal 

The sihl-starter project should be cloned in order to start an app. It should showcase the most crucial parts of a typical web app. It should provide a sensible folder structure.

## Features

- Custom command
- Custom seed
- Unit tests
- Integration tests
- Split app/web/services
- HTML rendering (with conformist form)
- JSON API
- CI Setup
- docker-compose
- Makefile

**Comment by aronerben** [comment]
TODO:
- Create demo project of pizza vendor
- Remove minimal starter (contained in  Sihl README)
- Remove starter (contained in demo)

**Comment by jerben** [comment]
We are working on a full example app but the main way to start a project is using spin.
