### ISSUE TITLE
Create contributor guide with best practices

### ISSUE THREAD

**Issue by jerben** [oxidizing/sihl#365]
## Goal

Idioms and conventions used in the Sihl code base should be documented in a contributor guide.

**Comment by dangdennis** [comment]
Any initial thoughts here aside from following the style present?

**Comment by jerben** [comment]
Hey @dangdennis 

If you want to contribute and need some pointers just let me or @aronerben know. Any PRs are greatly appreciated :)
The plan was to work on this in the 1.0.0 release but if there is interest we can start already.
In general, we try to follow the style of https://github.com/rgrinberg/opium.

**Comment by dangdennis** [comment]
Thank you for your willingness to help.

It’ll be a slow learning and exploration process as I’m looking for a safe use case for ocaml at my company.
