### ISSUE TITLE
Allow registration of multiple service implementations of the same type

### ISSUE THREAD

**Issue by jerben** [oxidizing/sihl#366]
## Goal

It should be possible to register multiple implementations (even same implementation) of a service type. Referring to it while using the facade overrides the registered service.

```ocaml
let services =
  [ Sihl.Database.Migration.(register ~migrations Implementation.postgresql)
  ; Sihl.Token.(register Implementation.postgresql)
  ; Sihl.Email_template.(register Implementation.postgresql)
  ; Sihl.User.(register Implementation.postgresql)
  ; Sihl.Session.(register Implementation.postgresql)
  ; Sihl.Token.(register Implementation.postgresql)
  ; Sihl.Queue.(register ~jobs Implementation.postgresql)
  ; Sihl.User.Password_reset.register ()
  ; email_default
  ; email_marketing
  ; Sihl.Schedule.register ()
  ; Sihl.Web.register Web.Route.all
  ]
```

**Comment by aronerben** [comment]
@jerben As decided, let's re-functorize all services that need to be with the following points:
- Functorize stuff that needs to be configurable (`Sihl.Email.MakeSmtp (MarketingConfig)`)
- Remove all facades
- Add the `register` functions to the top level of the modules (not inside the `Make` functors)
- Add to design goals: If Sihl app simple, never have to use functors (plumbing should very easy), if Sihl app complex, need to read docs and see exactly how to do it and wire everything up

Reasons why we're going back to functors:
- Many dependencies vanished in prior iterations => Fewer functors needed
- Common way for modular dependency injection
- Removes a lot of overhead (facades, choosing which implementation at runtime) and global state
