### ISSUE TITLE
Replace session service with cache service

### ISSUE THREAD

**Issue by jerben** [oxidizing/sihl#375]
## Goal

We want to be able to store handles/references using the cookie backed session middleware, where the value that should be hidden from the client is stored in this generic cache service.

## Todo

- rename session service
- make sure to document the service implementations (the cache can be used as key value store depending on them implementation

## Notes

This should be the main part of the API:

```ocaml
val set : t -> (string * string option) -> unit Lwt.t
val find : t -> string -> string option Lwt.t
```

**Comment by aronerben** [comment]
@jerben Closing.
