### ISSUE TITLE
Add HTMX helpers

### ISSUE THREAD

**Issue by jerben** [oxidizing/sihl#392]

**Comment by dangdennis** [comment]
What’re you planning? I just checked out htmx,  https://htmx.org/. super nifty lib that can really add some dynamism to HTML without the hassle of SPAs. 

While the lib makes sense, I’m curious why you would need a specific middleware.

**Comment by jerben** [comment]
This was actually already implemented here: https://oxidizing.github.io/sihl/sihl/Sihl/Web/Htmx/index.html

They are just helpers to make dealing with HTMX headers a bit safer. The short-term plan is to embrace HTMX in the documentation, the long-term plan is to provide CLI generators for views, forms and routes that use HTMX. 

It might make sense to get rid of the middleware though and directly manipulate the HTTP headers.
