### ISSUE TITLE
Simplify CSRF Protection

### ISSUE THREAD

**Issue by aronerben** [oxidizing/sihl#400]
Since we now use Cookies as our Session backend, we can simply use the [Double Submit Cookie](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie) approach.
- [x] Create a new CSRF token on every request (avoid BREACH attack), not just when it is consumed
- [x] Hash the CSRF token that is sent in the cookie
- [x] Use a separate `_csrf` cookie (instead of the session cookie `_session`) to store the CSRF token
- [x] Disable CSRF in dev mode (settable with env var)

**Comment by aronerben** [comment]
@jerben How about we also disable CSRF in dev mode?

**Comment by jerben** [comment]
@aronerben What is the benefit of that?I think dev mode should be as close as possible to production.

**Comment by aronerben** [comment]
@jerben It can be very annoying to work on views that require CSRF protection. You can't just resubmit the request over and over again to develop, you have to go back to the form and fill everything out and resubmit.

**Comment by jerben** [comment]
@aronerben Valid point I agree, let's do it.

**Comment by aronerben** [comment]
@jerben How would we go about this? Check for a env in the middleware?

**Comment by jerben** [comment]
@aronerben Yes exactly

**Comment by aronerben** [comment]
- [ ] Add disable for dev and add it to docs too
