### ISSUE TITLE
Harden CSRF cookie handling

### ISSUE THREAD

**Issue by aronerben** [oxidizing/sihl#408]
Since we want to use a separate cookie key, for example `_csrf`, with more restrictions than the `_session` cookie, we have to make sure the cookie is not shared on subdomains and check for various other sensible cookie settings. Check this: https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#cookie-with-__host-prefix

**Comment by jerben** [comment]
## Todo

- by default the cookie name should be `__Host-csrf` instead of `_csrf`
- set cookie path to `/`
- mark cookie `Secure`
