### ISSUE TITLE
Think about dashboard style

### ISSUE THREAD

**Issue by jerben** [oxidizing/sihl#440]
It should be somewhat possible to overwrite the default theme. Maybe we can provide multiple themes.

It should be possible to disable the default style.

**Comment by aronerben** [comment]
@jerben I propose we add semantic class names to certain elements, for example for queue dashboard `job-row`, `job-row-field`, `job-row-requeue-button` etc.
Additionally we provide two default themes: A minimalist/simple light and dark theme. Those can be disabled and custom styling can be applied with the classes. What do you think?
Should we also make it mobile-accessible?

**Comment by jerben** [comment]
@aronerben I like it, sounds like a plan! Mobile might be tricky, I'd say let's postpone that. We need to think about how to package the themes.

**Comment by aronerben** [comment]
Polymorphic variant `'Light, 'Dark, 'Custom url`, inline css with `<style>` tags, append to body
