### ISSUE TITLE
Generator adds postgres dependency when mariadb is specified

### ISSUE THREAD

**Issue by mabiede** [oxidizing/sihl#497]
@jerben 

When generating a new model with `gen.html` (or similar) the dune file in the unit test folder always depends on `caqti-driver-postgresql` even if `mariadb` is specified as DB of choice.

Looks like the following line is in charge of this:
https://github.com/oxidizing/sihl/blob/2ebf8b0faba442e955c3595f01df85413d855bf7/sihl/src/gen_model_test.ml#L76

**Comment by mabiede** [comment]
e.g. from model generator
```
let dune_file_template database =
  let open Gen_core in
  match database with
  | PostgreSql ->
    {|
      (test
        (name test_{{name}})
        (libraries sihl service database alcotest alcotest-lwt
          caqti-driver-postgresql {{name}}))
    |}
  | MariaDb ->
    {|
      (test
        (name test_{{name}})
        (libraries sihl service database alcotest alcotest-lwt
          caqti-driver-mariadb {{name}}))
    |}
;;
```

**Comment by jerben** [comment]
Thanks @mabiede for the bug report and providing the fix already. I am merging it now.

**Comment by jerben** [comment]
Fixed by https://github.com/oxidizing/sihl/commit/b34d2fd7bd871bc218628a1bbe25679c6bd46788
