### ISSUE TITLE
Make sure `PREFIX_PATH` is taken into account for routes

### ISSUE THREAD

**Issue by aronerben** [oxidizing/sihl#498]
Currently, if a `PREFIX_PATH` is set, it is ignored for routes. 
So with `PREFIX_PATH=staging` and this route:
```ocaml
let public =
  [ get "/welcome" Handler.Public.welcome ]
```

The route is served under `localhost:3000/welcome` but it should be `localhost:3000/staging/welcome`.

**Comment by jerben** [comment]
@aronerben Thanks for providing a PR with the issue!
