### ISSUE TITLE
What’s the deployment strategy like for Sihl?

### ISSUE THREAD

**Issue by dangdennis** [oxidizing/sihl#503]
I’ve started a Sihl project, and the first thing I usually like to do first is to deploy the app onto a live server ASAP.

Any services that you prefer for hosting? Do you prefer containerizing it?

**Comment by jerben** [comment]
Hey @dangdennis 

> I’ve started a Sihl project, and the first thing I usually like to do first is to deploy the app onto a live server ASAP.

Sensible approach, please let me know if you encounter any issues in the process. :)

> Do you prefer containerizing it?

All Sihl deployments that I know are running on Docker. In the final container image we have the compiled binary, the system dependencies installed with `opam depext` and the folder with the static files. We also have a reverse proxy taking the requests and forward them to Sihl, but the static files are served by Sihl. No issues with that so far, httpaf does a great job.

> Any services that you prefer for hosting? 

Anything that runs Docker. We have deployed on a DO droplet running Docker and on a custom infrastructure with container orchestration using Docker Swarm.
