### ISSUE TITLE
user_from_session context

### ISSUE THREAD

**Issue by timohuber** [oxidizing/sihl#518]
`Service.User.Web.user_from_session` should accept a context to be used with multi tenancy, like:
```
let user_from_session find_user ?ctx ?cookie_key ?secret ?(key = "user_id") req
    : Sihl.Contract.User.t option Lwt.t
  =
  match Sihl.Web.Session.find ?cookie_key ?secret key req with
  | Some user_id -> find_user ?ctx user_id
  | None -> Lwt.return None
;;
```

**Comment by aronerben** [comment]
Thanks @timohuber, seems like that function went under the radar :) 
Added in https://github.com/oxidizing/sihl/pull/519

**Comment by aronerben** [comment]
@timohuber Please close if this has been resolved
