### ISSUE TITLE
Turning off `FOREIGN_KEY_CHECK` doesn't work for migrations.

### ISSUE THREAD

**Issue by mabiede** [oxidizing/sihl#526]
## Behavior

Even though the argument `?check_fk` is set as `~check_fk:false` the `FOREIGN_KEY` gets checked and raises an error.

## Investigation

- Running the Migrations with the argument set to `true` or `false` results in the same error
- Running the Migration steps manually with disabling the key check before and enabling it after works as expected

## Solution

The migrations are using the database function [`Sihl.Database.exec`](https://github.com/oxidizing/sihl/blob/bfa5c7924bb573cfcdc2bd8f689dd55999800cc6/sihl/src/database.ml#L345). This `exec` function creates its own connection (and doesn't use the same as the parent one).

One of these two options should solve it:
- Add optional input argument for `Sihl.Database.exec`
- Use `Connection.exec` instead of `Database.exec` in `execute_steps` (Make sure `~ctx` is handled) [here](https://github.com/oxidizing/sihl/blob/bfa5c7924bb573cfcdc2bd8f689dd55999800cc6/sihl/src/database_migration.ml#L132)

@joseferben @aronerben I guess this bug was introduced with the implementation of the database `ctx`.

**Comment by joseferben** [comment]
@mabiede Thanks for the report, this should be fixed with: https://github.com/oxidizing/sihl/pull/527
