### ISSUE TITLE
sihl 0.3.0: tarball changed

### ISSUE THREAD

**Issue by mseri** [oxidizing/sihl#533]
In the opam repository we are seeing the following failure
```
OpamSolution.Fetch_fail("https://github.com/oxidizing/sihl/archive/0.3.0.tar.gz (Bad checksum, expected md5=3265ccfac470edc97a524259ec98e15b)")
```
Do you still have the original tarball somewhere?

**Comment by joseferben** [comment]
@mseri 
If I get the tarball for 0.3.0 from the release page https://github.com/oxidizing/sihl/releases/tag/0.3.0 using https://github.com/oxidizing/sihl/archive/refs/tags/0.3.0.tar.gz:

```
$ md5sum sihl-0.3.0.tar.gz 
3265ccfac470edc97a524259ec98e15b
```
