### ISSUE TITLE
Add meta field to Sihl_queue jobs

### ISSUE THREAD

**Issue by mabiede** [oxidizing/sihl#545]
The goal is to store additional information about a specific job, e.g. who was the submitter or detailed job information.

- Add a `meta` or `job_meta` field to the `Sihl_queue` jobs
- The value can be a string or customized e.g. stringified JSON
- Add `?meta` as an optional input argument to job functions which can be queued
- The field affects only queued jobs, in all other cases, the argument has no effect

**Comment by joseferben** [comment]
@mabiede If I understand correctly, adding meta data wouldn't make it easier for users to filter/search jobs? You'd still have to access the database directly right? 

So we need some search API anyway:
```ocaml
  let search ?ctx ?(sort = `Desc) ?filter ?(limit = 50) ?(offset = 0) () =
    Repo.search ?ctx sort filter ~limit ~offset
  ;;
```

Wouldn't it be possible to just add the meta data to the actual job instance yourself and then use the provided API to search? I think to justify a `meta` field we'd have to treat the meta data a bit different from the job instance data.

**Comment by joseferben** [comment]
Closing for now since we implemented a searchable tag for this purpose.
