### ISSUE TITLE
Interest in converting to an eio based project?

### ISSUE THREAD

**Issue by dangdennis** [oxidizing/sihl#546]
With eio available, it is possible incrementally migrate to eio with lwt-eio. https://github.com/ocaml-multicore/lwt_eio

The value proposition here is the direct style programming as well as easy performance wins.

The migration plan can first be a minor version upgrade to switch to the eio event loop. Then major could remove the entire lwt stack. 

Risks and blockers
1. Not all libraries are ready for ocaml 5.  May delay a major version.
2. Lwt-eio introduces possible runtime errors that may require debugging. Minor version can introduce new bugs.

**Comment by joseferben** [comment]
Switching to eio is definitely on the roadmap. Right now we are waiting for cohttp-eio to mature a bit more.
