### ISSUE TITLE
Migrate away from Nocrypto

### ISSUE THREAD

**Issue by leostera** [oxidizing/sihl#562]
Hi folks! 

I've been trying to get Sihl up and running in a number of environments, and I noticed that you're still relying on Nocrypto, which has been deprecated.

Would you be open to a PR moving from nocrypto to an alternative like mirage-crypto?

**Comment by joseferben** [comment]
Hi @leostera

Thanks for going ahead and opening a PR, would be super interested to know if you ran into any issues setting up Sihl.

**Comment by joseferben** [comment]
implemented: https://github.com/oxidizing/sihl/pull/563
