### ISSUE TITLE
Support watching files and restarting server

### ISSUE THREAD

**Issue by jerben** [oxidizing/sihl#75]
https://github.com/kandu/ocaml-fswatch/

**Comment by mikonieminen** [comment]
This can be achived by something like (using for starting `sihl-starter` project):
```ocaml
(rule
  (alias run)
  (action
   (setenv LOG_LEVEL debug
    (run ./app.exe start)
   )
  )
)
```
And then running `dune build --watch @run`.

Only issue is that the output is lost completely and I'm not quite sure why. When dropping that `start`, I can see the help messages in `stdout`, but when started in server, mode there's nothing.

**Comment by jerben** [comment]
Fixed here: https://github.com/oxidizing/spin-sihl/blob/main/template/Makefile#L62

**Comment by aronerben** [comment]
> Fixed here: https://github.com/oxidizing/spin-sihl/blob/main/template/Makefile#L62

Is this supposed to say `.PHONE dev`?
https://github.com/oxidizing/spin-sihl/blob/main/template/Makefile#L59

**Comment by aronerben** [comment]
@jerben I've gotten feedback that this script does not work well on macOS.
They had to use `kill -9 $$(lsof -ti tcp:3000)` to kill the process and `SHELL = zsh` to make sure all the commands are correctly recognized. FYI.
